"""IRC numeric reply codes (RFC 2812 §5)."""

# Connection registration
RPL_WELCOME = "001"
RPL_YOURHOST = "002"
RPL_CREATED = "003"
RPL_MYINFO = "004"

# Channel
RPL_LISTSTART = "321"
RPL_LIST = "322"
RPL_LISTEND = "323"
RPL_TOPIC = "332"
RPL_NOTOPIC = "331"
RPL_NAMREPLY = "353"
RPL_ENDOFNAMES = "366"

# Mode
RPL_UMODEIS = "221"
RPL_CHANNELMODEIS = "324"

# Discovery
RPL_WHOISUSER = "311"
RPL_WHOISSERVER = "312"
RPL_ENDOFWHOIS = "318"
RPL_WHOISCHANNELS = "319"
RPL_WHOREPLY = "352"
RPL_ENDOFWHO = "315"

# Errors
ERR_NOSUCHNICK = "401"
ERR_NOSUCHSERVER = "402"
ERR_NOSUCHCHANNEL = "403"
ERR_CANNOTSENDTOCHAN = "404"
ERR_UNKNOWNCOMMAND = "421"
ERR_NONICKNAMEGIVEN = "431"
ERR_ERRONEUSNICKNAME = "432"
ERR_NICKNAMEINUSE = "433"
ERR_USERNOTINCHANNEL = "441"
ERR_NOTONCHANNEL = "442"
ERR_NEEDMOREPARAMS = "461"
ERR_ALREADYREGISTRED = "462"
ERR_CHANOPRIVSNEEDED = "482"
ERR_USERSDONTMATCH = "502"

# Error/reply message texts
MSG_NEEDMOREPARAMS = "Not enough parameters"
MSG_NOSUCHCHANNEL = "No such channel"
MSG_NOSUCHNICK = "No such nick"
MSG_NOTONCHANNEL = "You're not on that channel"
MSG_ENDOFWHO = "End of WHO list"
MSG_NOSUCHTHREAD = "No such thread"
